name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    permissions:
      contents: write
    with:

      node-version: 22
      pnpm-version: 9
      java-version: 21
      app-id: app-2zcenro1
